Sync CLI Integeration
browserstack/browserstack-gradle-plugin pull request #57
Opened 2022-09-22 07:53 UTC by richaArora08

2022-09-29 13:52 UTC, gshah30 approved these changes

2022-09-30 08:55 UTC, deepwired requested changes
We need to bump the version to be able to test.
https://github.com/browserstack/browserstack-gradle-plugin/pull/55/files

2022-09-30 08:55 UTC, deepwired commented on test.rb
> +  run_basic_espresso_test("./gradlew browserstackCLIWrapper -Pcommand='app-automate apps delete -a bs://3fc4eea395ea6efc69b74e8211ecf2eba8879373'")
This test won't work every time right?

2022-09-30 09:11 UTC, deepwired approved these changes

2022-09-30 09:18 UTC, merged