Let Users pass dynamic path to read main and test apks
browserstack/browserstack-gradle-plugin pull request #68
Opened 2023-01-02 10:09 UTC by richaArora08

2023-01-02 11:27 UTC, deepwired requested changes

2023-01-02 11:27 UTC, deepwired commented on test.rb
> +  run_espresso_test_with_path("./gradlew executeDebugTestsOnBrowserstack -PmainAPKPath=#{mainAPKPath} -PtestAPKPath=#{testAPKPAth}")
lets add a unit test for dynamic path + config file with instrumentation, cucumber options?

2023-01-02 11:27 UTC, deepwired commented on test.rb
> +  run_espresso_test_with_path("./gradlew executeDebugTestsOnBrowserstack -PmainAPKPath=#{mainAPKPath} -PtestAPKPath=#{testAPKPAth}")
Lets also add a negative scenario where an apk is not present in the provided path

2023-01-02 11:27 UTC, deepwired commented on src/main/java/com/browserstack/gradle/BrowserStackTask.java
>      Files.find(Paths.get(dir), Constants.APP_SEARCH_MAX_DEPTH, (filePath, fileAttr) -> isValidFile(filePath, fileAttr))
if both paths are provided no need to execute below loop on files

2023-01-02 11:27 UTC, deepwired commented on src/main/java/com/browserstack/gradle/BrowserStackTask.java
>            if (f.toString().endsWith("-androidTest.apk")) {
might as well combine these if statements `!isAPKFileCreated[1] && f.toString().endsWith("-androidTest.apk")`

2023-01-02 12:19 UTC, richaArora08 commented on src/main/java/com/browserstack/gradle/BrowserStackTask.java
>      Files.find(Paths.get(dir), Constants.APP_SEARCH_MAX_DEPTH, (filePath, fileAttr) -> isValidFile(filePath, fileAttr))
Ok.

2023-01-03 04:13 UTC, richaArora08 commented on src/main/java/com/browserstack/gradle/BrowserStackTask.java
>            if (f.toString().endsWith("-androidTest.apk")) {
Done

2023-01-03 09:18 UTC, deepwired requested changes

2023-01-03 09:18 UTC, deepwired commented on test.rb
> +def run_test_with_incorrect_path
add variations, print statements
- when testapk path is provided
- when aut path is provided
- when both is provided

2023-01-04 02:46 UTC, deepwired submitted a review, later dismissed
LGTM

2023-01-05 05:32 UTC, deepwired commented on test.rb
> +    puts "✘ #{gradle_command} failed with error: #{responses}".red
if we are expecting this unit test to fail, can we change the color idication to green here, and red for the else condition?

2023-01-05 06:33 UTC, deepwired commented on test.rb
> +    puts "✘ #{gradle_command} failed with error: #{responses}".red
resolved.

2023-01-05 06:40 UTC, deepwired submitted a review, later dismissed

2023-01-12 06:18 UTC, sauravdas1997 commented on test.rb
> +  testAPKPAth =  $current_path + "/test/mainApk/ipa"
This will pick the same app, can we point it to any other path with apk test

2023-01-12 06:41 UTC, richaArora08 commented on test.rb
> +  testAPKPAth =  $current_path + "/test/mainApk/ipa"
Changes pushed.

2023-01-12 07:02 UTC, sauravdas1997 approved these changes

2023-01-12 07:29 UTC, deepwired approved these changes
LGTM

2023-01-12 07:54 UTC, merged